<a href="https://colab.research.google.com/github/Pratik00019/ANN-for-BANKS/blob/main/ANN_Banks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="45px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>What is Colaboratory?</h1>

Colaboratory, or "Colab" for short, allows you to write and execute Python in your browser, with 
- Zero configuration required
- Free access to GPUs
- Easy sharing

Whether you're a **student**, a **data scientist** or an **AI researcher**, Colab can make your work easier. Watch [Introduction to Colab](https://www.youtube.com/watch?v=inN8seMm7UI) to learn more, or just get started below!



```
# IMPORTING LIBRARIES
```

# DATA PREPROCESSING

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [6]:
dataset=pd.read_csv("Churn_Modelling.csv")
X=dataset.iloc[:, 3:-1].values
y=dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:, 2]=le.fit_transform(X[:, 2])


In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1] )],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


In [9]:
from sklearn.model_selection import train_test_split
#random state is used to produce the same result when we run multiple times
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=0) 
print(X_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [10]:
#FEATURE SCALING
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
"""The fit method is calculating the mean and variance of each of the features present in our data. The transform method is transforming all the features using the respective mean and variance.
Now, we want scaling to be applied to our test data too and at the same time do not want to be biased with our model. We want our test data to be a completely new and a surprise set for our model. The transform method helps us in this case
Using the transform method we can use the same mean and variance as it is calculated from our training data to transform our test data. Thus, the parameters learned by our model using the training data will help us to transform our test data."""
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


# BUILDING THE ANN

In [11]:
#INITIALZING THE ANN
ann=tf.keras.models.Sequential()

ADDING THE FIRST LAYER AND INPUT LAYER

In [12]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

ADDING THE SECOND LAYER

In [13]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

ADDING THE OUTPUT LAYER

In [14]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# TRAINING THE ANN

Compiling the ANN

In [15]:
ann.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

Training the ANN

In [16]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5795 - accuracy: 0.7534
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4813 - accuracy: 0.8016
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4382 - accuracy: 0.8131
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4178 - accuracy: 0.8181
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4034 - accuracy: 0.8238
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3909 - accuracy: 0.8295
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3807 - accuracy: 0.8357
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3722 - accuracy: 0.8411
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3661 - accuracy: 0.8465
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3618 - accura

Predicting a single result

In [21]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


# Predicting with the test set

In [30]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
